(require 'font-settings)
(require 'global-keybindings)
(require 'misc-settings)
(require 'c-settings)
(require 'python-settings)
(require 'org-settings)
(require 'yas-settings)
(require 'js2-settings)
(require 'html-settings)
(require 'shell-settings)
(require 'markdown-settings)
(require 'ido-settings)

(provide 'my-settings)
